#!/usr/bin/env bash
set -euo pipefail

AUDIT_DIR="docs/audits/2026-04-16-legion-4-7"
DB="$AUDIT_DIR/FINDINGS-DB.jsonl"
INDEX="$AUDIT_DIR/INDEX.md"

TOTAL=$(wc -l < "$DB" | tr -d ' ')
# Note: `grep -c ... || echo 0` is double-counting on empty DB (grep prints 0
# AND exits 1, so the `|| echo 0` fires and appends a second 0). Suppress the
# non-match exit via `|| true` so the real zero from grep is preserved.
P0=$(grep -c '"severity":"P0"' "$DB" || true)
P1=$(grep -c '"severity":"P1"' "$DB" || true)
P2=$(grep -c '"severity":"P2"' "$DB" || true)
P3=$(grep -c '"severity":"P3"' "$DB" || true)

AUDITED_COUNT=$(find "$AUDIT_DIR/findings" -name "*.md" -not -name ".gitkeep" | wc -l | tr -d ' ')

cat > "$INDEX.tmp" <<EOF
# Audit Index — Legion v7.3.2 → v7.4.0

**Audit started:** 2026-04-16
**Rubric version:** 1.0
**Baseline tag:** audit-v47-baseline
**Status:** in_progress ($AUDITED_COUNT / 125 files audited)

## Summary by Severity

- P0: $P0 findings
- P1: $P1 findings
- P2: $P2 findings
- P3: $P3 findings
- **Total:** $TOTAL findings

## Summary by Category

| Category | Count | Max Severity |
|----------|-------|--------------|
EOF

for CAT in CAT-1 CAT-2 CAT-3 CAT-4 CAT-5 CAT-6 CAT-7 CAT-8 CAT-9 CAT-10; do
  COUNT=$(grep -c "\"category\":\"$CAT\"" "$DB" || true)
  MAX_SEV=$(grep "\"category\":\"$CAT\"" "$DB" 2>/dev/null | grep -oE '"severity":"P[0-3]"' | sort | head -n 1 | grep -oE 'P[0-3]' || echo "-")
  echo "| $CAT | $COUNT | $MAX_SEV |" >> "$INDEX.tmp"
done

echo "" >> "$INDEX.tmp"
echo "## Files" >> "$INDEX.tmp"
echo "" >> "$INDEX.tmp"
echo "See per-layer index sections generated by hand or re-run this script." >> "$INDEX.tmp"
echo "Findings files live under \`findings/\` by layer." >> "$INDEX.tmp"

mv "$INDEX.tmp" "$INDEX"
echo "INDEX.md updated. $AUDITED_COUNT / 125 audited, $TOTAL findings."
